apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: container-config
      image: 252155551832.dkr.ecr.sa-east-1.amazonaws.com/softfocus/config:latest
      ports:
        - containerPort: 80
